apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:

# argocd with argocd-lovelvy und vault plugin
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml

# argocd projects & applicationssets
- ./manifests/

patches:
  - path: patches/argo-cm.yml
    target:
      kind: ConfigMap
      name: argocd-cm
  - path: patches/argocd-lovely-plugin.yml
    target:
      kind: Deployment
      name: argocd-repo-server
  - path: patches/argocd-vault-replacer.yml
    target:
      kind: Deployment
      name: argocd-repo-server
